// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package thrift_interface

import (
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
)

// (needed to ensure safety because of naive import list construction.)
var _ = math.MinInt32
var _ = thrift.ZERO
var _ = fmt.Printf

type SecureService interface {
	CommonService

	// Parameters:
	//  - CommonRequest
	//  - PlainText
	CipherPlainText(commonRequest *CommonRequest, plainText string) (r string, err error)
}

type SecureServiceClient struct {
	*CommonServiceClient
}

func NewSecureServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *SecureServiceClient {
	return &SecureServiceClient{CommonServiceClient: NewCommonServiceClientFactory(t, f)}
}

func NewSecureServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *SecureServiceClient {
	return &SecureServiceClient{CommonServiceClient: NewCommonServiceClientProtocol(t, iprot, oprot)}
}

// Parameters:
//  - CommonRequest
//  - PlainText
func (p *SecureServiceClient) CipherPlainText(commonRequest *CommonRequest, plainText string) (r string, err error) {
	if err = p.sendCipherPlainText(commonRequest, plainText); err != nil {
		return
	}
	return p.recvCipherPlainText()
}

func (p *SecureServiceClient) sendCipherPlainText(commonRequest *CommonRequest, plainText string) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	oprot.WriteMessageBegin("cipherPlainText", thrift.CALL, p.SeqId)
	args35 := NewCipherPlainTextArgs()
	args35.CommonRequest = commonRequest
	args35.PlainText = plainText
	err = args35.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return
}

func (p *SecureServiceClient) recvCipherPlainText() (value string, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	_, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error37 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error38 error
		error38, err = error37.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error38
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "ping failed: out of sequence response")
		return
	}
	result36 := NewCipherPlainTextResult()
	err = result36.Read(iprot)
	iprot.ReadMessageEnd()
	value = result36.Success
	return
}

type SecureServiceProcessor struct {
	*CommonServiceProcessor
}

func NewSecureServiceProcessor(handler SecureService) *SecureServiceProcessor {
	self39 := &SecureServiceProcessor{NewCommonServiceProcessor(handler)}
	self39.AddToProcessorMap("cipherPlainText", &secureServiceProcessorCipherPlainText{handler: handler})
	return self39
}

type secureServiceProcessorCipherPlainText struct {
	handler SecureService
}

func (p *secureServiceProcessorCipherPlainText) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := NewCipherPlainTextArgs()
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("cipherPlainText", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return
	}
	iprot.ReadMessageEnd()
	result := NewCipherPlainTextResult()
	if result.Success, err = p.handler.CipherPlainText(args.CommonRequest, args.PlainText); err != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing cipherPlainText: "+err.Error())
		oprot.WriteMessageBegin("cipherPlainText", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return
	}
	if err2 := oprot.WriteMessageBegin("cipherPlainText", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 := result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 := oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 := oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

type CipherPlainTextArgs struct {
	CommonRequest *CommonRequest `thrift:"commonRequest,1"`
	PlainText     string         `thrift:"plainText,2"`
}

func NewCipherPlainTextArgs() *CipherPlainTextArgs {
	return &CipherPlainTextArgs{}
}

func (p *CipherPlainTextArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error", p)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *CipherPlainTextArgs) readField1(iprot thrift.TProtocol) error {
	p.CommonRequest = NewCommonRequest()
	if err := p.CommonRequest.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.CommonRequest)
	}
	return nil
}

func (p *CipherPlainTextArgs) readField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 2: %s")
	} else {
		p.PlainText = v
	}
	return nil
}

func (p *CipherPlainTextArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("cipherPlainText_args"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("%T write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("%T write struct stop error: %s", err)
	}
	return nil
}

func (p *CipherPlainTextArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if p.CommonRequest != nil {
		if err := oprot.WriteFieldBegin("commonRequest", thrift.STRUCT, 1); err != nil {
			return fmt.Errorf("%T write field begin error 1:commonRequest: %s", p, err)
		}
		if err := p.CommonRequest.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.CommonRequest)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 1:commonRequest: %s", p, err)
		}
	}
	return err
}

func (p *CipherPlainTextArgs) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("plainText", thrift.STRING, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:plainText: %s", p, err)
	}
	if err := oprot.WriteString(string(p.PlainText)); err != nil {
		return fmt.Errorf("%T.plainText (2) field write error: %s", p)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:plainText: %s", p, err)
	}
	return err
}

func (p *CipherPlainTextArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CipherPlainTextArgs(%+v)", *p)
}

type CipherPlainTextResult struct {
	Success string `thrift:"success,0"`
}

func NewCipherPlainTextResult() *CipherPlainTextResult {
	return &CipherPlainTextResult{}
}

func (p *CipherPlainTextResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error", p)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.readField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *CipherPlainTextResult) readField0(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 0: %s")
	} else {
		p.Success = v
	}
	return nil
}

func (p *CipherPlainTextResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("cipherPlainText_result"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	switch {
	default:
		if err := p.writeField0(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("%T write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("%T write struct stop error: %s", err)
	}
	return nil
}

func (p *CipherPlainTextResult) writeField0(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("success", thrift.STRING, 0); err != nil {
		return fmt.Errorf("%T write field begin error 0:success: %s", p, err)
	}
	if err := oprot.WriteString(string(p.Success)); err != nil {
		return fmt.Errorf("%T.success (0) field write error: %s", p)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 0:success: %s", p, err)
	}
	return err
}

func (p *CipherPlainTextResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CipherPlainTextResult(%+v)", *p)
}
